logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safebike
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    async:
      request-timeout: 300000

vaadin:
  pwa:
    enable: true
  launch-browser: true

jwt:
  secret: MySecretKeyForJWTTokenGenerationThatMustBeAtLeast512BitsLongForHS512AlgorithmToWorkProperlyAndSecurely123456789
  expiration: 86400

server:
  port: 8080
  address: 0.0.0.0  # Permite acceso desde otros dispositivos en la red
  connection-timeout: 300000
  tomcat:
    max-swallow-size: 50MB