logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safebike
    username: juant
    password: loki2019
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

vaadin:
  pwa:
    enable: true
  launch-browser: true

jwt:
  secret: myVeryLongAndSecureSecretKeyThatIsAtLeast64CharactersToMeetHS512Standard!
  expiration: 86400

server:
  port: 8080
  address: 0.0.0.0  # Permite acceso desde otros dispositivos en la red